# Site settings
title: CapsOp
name: CapsOp
description: >
  IT-Security blog of wirehack7. Writing about malware hunting, botnet shutdowns,
  pentesting and securing IT architecture.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://capsop.com" # the base hostname & protocol for your site
timezone: "Europe/Berlin"
encoding: utf-8

author:
  fullname: wirehack7
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: wirehack7
  twitter: wirehack7
  # disqus: your_disqus_forum_shortname

# Analytics settings
# google_analytics: 'UA-XXXXXXXX-X'
piwik_url: '//piwik.capsop.com/'
piwik_id: 1
piwik_domains: "*.capsop.com"
piwik_img: "//piwik.capsop.com/piwik.php?idsite=1"

# Syntax highlighting
highlightstyle: 'railscast'
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html","Gemfile"]

# Build settings
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM